### ISSUE TITLE
SNSアカウントの運用について

### ISSUE THREAD

**Issue by gouten5010** [npo-skn-nagaoka/nagaokaplayers#11]

**Comment by Haruka-Hirokawa** [comment]
◎Twitter
現在はbotでの運用

【課題】
・自動ツイートなので一方通行的になりやすい
・人間味、親近感を持ちにくい
・活動していることが分かりにくい

【改善策】
●コミュニケーション要素を出す
・フォロー、フォロワーのツイートにリプライ→団体同士の交友関係も分かる
・フォロワーをリツイート
　（Twitterのリスト機能を活用しリツイート対象はある程度絞った方がOK）
・シェア目的ではない雑談みたいなものでもOK
・写真も掲載するとなお良い


●定期的につぶやくことへの負担感をなくす
・つぶやきやリプライする時間を決める
・期間限定のキャンペーンみたいな感じでTwitter運用してみては？
　→上手くいけばその後も続けてみる、とか


◎Facebook

【課題】
委託事業(センター事業)との差別化があまりできていない、分かりづらい


【改善策】

**Comment by Haruka-Hirokawa** [comment]
◎Twitter
現在はbotでの運用

【課題】
・自動ツイートなので一方通行的になりやすい
・人間味、親近感を持ちにくい
・活動していることが分かりにくい

【改善策】
●認知度を広める
・ハッシュタグをつけてつぶやく

●コミュニケーション要素を出す
・フォロー、フォロワーのツイートにリプライ→団体同士の交友関係も分かる
・フォロワーをリツイート
　（Twitterのリスト機能を活用しリツイート対象はある程度絞った方がOK）
・シェア目的ではない雑談みたいなものでもOK
・写真も掲載するとなお良い

●定期的につぶやくことへの負担感をなくす
・つぶやきやリプライする時間を決める
・期間限定のキャンペーンみたいな感じでTwitter運用してみては？
　→上手くいけばその後も続けてみる、とか


◎Facebook

【課題】
・委託事業(センター事業)との差別化があまりできていない、分かりづらい


【改善策】
・自主事業の発信
・プレイヤー図鑑のインタビューの裏側を見せる
　（オフィシャル行事(委託事業？)の裏側を見せる）

**Comment by Haruka-Hirokawa** [comment]
Twitter

●活動団体紹介
☆活動団体紹介☆
今回は、「　団体名　」です！
「　団体の簡単な紹介文　」
ご興味ある方はこちら→「　HPへのリンク　」

●イベント告知
「　(日時・)イベント名　」開催します！
「　イベントの簡単な紹介文　」
初めましても大歓迎☆
地域に興味がある方、皆とワイワイ盛り上がりたい方ぜひ！

●開催が近づいた
「　イベント名　」が近くなってきました！
　　　　　　　　　　あと◯日後です！
（　「　イベント名　」の収益金は、会場費など必要経費を除いた金額を、「　団体名？　」の活動に役立てさせていただきます。）
ぜひご参加をお待ちしております！

●開催当日
本日、「　時間・イベント名　」です！
飛び入り参加も大歓迎！
ぜひご参加をお待ちしております！

●開催中
ただ今、「　イベント名　」開催中です！
盛り上がってますよ〜！

**Comment by gouten5010** [comment]
Twitter ↑のブラッシュアップ

## 活動団体紹介
今回は「　団体名　」を紹介します！
「　団体の簡単な紹介文　」
ご興味ある方はこちら→「　HPへのリンク　」

## 開催が近づいた
### メインツイート
「　イベント名　」があと◯日後に迫ってきました！
ぜひご参加をお待ちしております！

### 自身にリプライまたは引用RTで補足情報
（　「　イベント名　」の収益金は、会場費など必要経費を除いた金額を、「　団体名？　」の活動に役立てさせていただきます。）

**Comment by Haruka-Hirokawa** [comment]
（kosgis(運営)さんが作成したドキュメントはGoogle Driveの方に入れたので、必要であればそちらも参照頂ければと思います）

###  **NAGAOKA PLAYERS  SNS運用のポイント**
以下に続きます↓

**Comment by Haruka-Hirokawa** [comment]
⒈


 ## Twitter：気軽に絡みたい 
多くの人と気軽に繋がることができるので、積極的にコミュニケーションしていきましょう。人間味、親近感を持ってもらえることが大切です。情報が流れやすい分、雑談や小ネタ的な投稿もOK。


 ### 【仕組み】
基本的には時系列で「タイムライン」に表示されるので、タイミングを逃すと見てもらえません。
また、ハッシュタグ（#から始まるワード）で知らない人ともコミュニケーションできるのが特徴で、大勢の人が言及しているキーワードは「トレンド」となります。


 ### 【利用者の特徴】
20代が最も多く利用しており、年代が高くなると男性の利用率が高い特徴があります。一般的には情報収集に使いながら、時々独り言を喋っている人がほとんどです。会ったことはなくても興味関心でゆるく繋がることができます。


 ### 【発信方法】
**まずは認知度UP**
- ハッシュタグをつけてつぶやく（ # 長岡 etc）
・検索されやすくする
・参加していきたいコミュニティのハッシュタグをつける

**コミュニケーションを取る**
- フォロー・フォロワーのツイートにリプライ
・団体同士の交友関係が分かる
- フォロー・フォロワーをリツイート・引用リツイート
・Twitterのリスト機能を活用しリツイート対象はある程度絞ると◯
・共感できるツイートはできるだけ「引用リツイート」して自分の感想や意見も伝えると◯
- 団体紹介やイベント告知の他、シェア目的ではない雑談や小ネタ的なつぶやきも◯
- 写真・動画も合わせて掲載するとなお良い
・写真は１枚にした方が比較的目に止まりやすい

**頻繁につぶやくことが負担なら**
- つぶやきやリプライする時間を固定
- 期間限定のキャンペーン的にTwitterを運用



 ### 【裏ワザ】
- トレンドのハッシュタグは「このネタでウチも遊んでみよう」と考えてみる 
→ 無理しなくても乗りやすいものでOKです。
- 1日3〜5ツイートくらいできるとコミュニケーションが楽しくなる 
→ 朝、昼、夜に1・2ツイートくらい。独り言でいいので思いを語りましょう。
- コミュニケーションが活性化してきたらTwitterの投票機能も使ってみる
→ 簡易アンケートが取れるので記事やイベントの参考になります。

**Comment by Haruka-Hirokawa** [comment]
⒉

## Facebook：正しい情報を伝えるよう心がける
比較的フォーマルで、リアルに近いコミュニケーションを取ることができます。お金にまつわる投稿も問題ありません。イベントなどで関係者を巻き込み人の輪で広げましょう。


### 【仕組み】
リアルなつながりを重視している反面、ページの投稿は広がりにくいです。「友達」関係のない人に情報を届かせるには広告しかありません（Facebookのプラットフォーム戦略です）。
「友達の友達の友達」くらいまでは広げられるよう、関係者の個人アカウントを巻き込み「人のつながり」で広めていくことを意識しましょう。

### 【利用者の特徴】
40代中心で男性ユーザーが多め。背景にはビジネス利用していることが多いと思われます。他のSNSと比べ、年配のユーザーが多いです。


### 【発信方法】

- Twitterでは発信しきれない詳細を掲載
・イベント告知・開催後の報告等
・写真・動画も合わせて掲載するとなお良い
- ウェブページに掲載されている記事の裏事情を掲載するのもあり
・（例）プレイヤー図鑑のインタビューの裏側

　

### 【裏ワザ】
- @ でメンションしたりシェアして人を巻き込む 
→ Facebook ページの投稿は広がりにくいため、ページに投稿したものは関係者（スタッフ、イベント関係者、講師などFacebookをやっている人全員）に紐づけましょう。そのような運用体制であることを周知し、あらかじめお願いと許可を得ているとスムーズです。
- 動画はFacebookページに直接投稿
 → 動画はYouTubeなどのURLを共有してもほとんど伸びません。
- ウェブページの記事はまず、Facebook ページでシェア
→ 公式が投稿したものを関係者がシェアすると「インサイト」で確認できます。
- Facebook インサイトでわかる投稿の時間帯は日本時間にすると-7時間 （3月から11月までは -8時間：8時が0時正午が20時） 
→ 特に反応の良い時間がわかりますが、昼か夜のどちらかを判断する程度でも。

**Comment by Haruka-Hirokawa** [comment]
⒊

## テンプレート文例（Twitterベース、Facebookは字数制限なしの為、下記＋αで詳細を追加すると◯）

### 活動団体紹介
今回は「　団体名　」を紹介します！
「　団体の簡単な紹介文　」
ご興味ある方はこちら→「　HPへのリンク　」

### イベント告知
「　(日時・)イベント名　」開催します！
「　イベントの簡単な紹介文　」
初めましても大歓迎☆
地域に興味がある方、皆とワイワイ盛り上がりたい方ぜひ！

### 開催が近づいた
「　イベント名　」があと◯日後に迫ってきました！
ぜひご参加をお待ちしております！

自身にリプライまたは引用RTで補足情報
「　イベント名　」の収益金は、会場費など必要経費を除いた金額を、「　団体名etc　」の活動に役立てさせていただきます。

### 開催当日
本日、「　時間・イベント名　」です！
飛び入り参加も大歓迎！
ぜひご参加をお待ちしております！

### 開催中
ただ今、「　イベント名　」開催中です！
盛り上がってますよ〜！

### 開催後
「　イベント名　」無事終了しました！
（　イベントの簡単な感想　）
ご参加頂いた皆様、ありがとうございました！
これからも、皆で一緒に長岡のまちを盛り上げていきましょう！
次回のご参加もお待ちしております！

**Comment by Haruka-Hirokawa** [comment]
⒋

## SNS利用にあたって意識しておくこと


 ### 一度発信された発言は、原則修正不可
特にTwitterは発言を編集できないため、削除するしかありません。しかし削除するリミットは発言して30秒以内と考えておきましょう。それ以降は訂正の発言をするしかありませんが、元の発言のほうが広まりやすいです。


 ### 投稿に関するチェックリスト

- [ ] 個人情報や秘密情報を公開していませんか？
- [ ] 他人の利益を損なう発言になっていませんか？
- [ ] 製品名、社名、商標などは正しい名称になっていますか？
- [ ] 違法性のある発言、誹謗中傷をしていませんか？
- [ ] 建設的、客観的な良識ある発言になっていますか？


 ### クレームや困ったときの対応案
スタンスに合わせて対応を決定してください。 重要なのは人によって対応を変えず、一貫した対応をとることです。

**言いがかりや会話にならないなど、返答しにくいコメントに対して**

- 「貴重なご意見ありがとうございました」のみ返す
- 「コメントありがとうございます」のみ返す
- 「いいね」のみ返す
- 　対応しない

**建設的なクレーム（提案）の場合**

- 「貴重なご意見ありがとうございました」のみ返す
- 「そのご意見を活かしたいので、私たちと一緒に活動しませんか？」と勧誘する
- 「いいね」のみ返す
- 　対応しない

**好意的な意見の場合**

- 「ありがとうございます！」のみ返す
- 「そうですね！〜についてはどう思われますか？」と共感しつつ次の会話につなげる
- 「いいね」のみ返す
- 　対応しない
