### ISSUE TITLE
キャッチフレーズ（サイトのdescription）を決定する

### ISSUE THREAD

**Issue by rocket-martue** [npo-skn-nagaoka/nagaokaplayers#13]

**Comment by Haruka-Hirokawa** [comment]
（案）

１人１人が、長岡のまちづくりのプレイヤーに。
長岡市民協働センターの運営や、様々な交流会、寄付イベントを企画・運営。
市民が笑顔でいきいきと生活できるまちづくりを目指すNPO法人です。

**Comment by magu3** [comment]
中間支援団体として、長岡のプレイヤーを支援するとともに、プレイヤー間の交流を深め、支え合い、高め合う風土を作っていくNPO法人です。市民協働センターの運営や、交流会、イベントの企画、寄付金の受付/分配を実施しています。

**Comment by miminari** [comment]
「長岡の未来を作るプレイヤーを応援しよう」
でFIX
