### ISSUE TITLE
トップのリード文

### ISSUE THREAD

**Issue by gouten5010** [npo-skn-nagaoka/nagaokaplayers#15]
* 見出し
* 概要

**Comment by Haruka-Hirokawa** [comment]
（案）テンプレの合体版みたい笑↓

１人１人が、長岡のまちづくりのプレイヤーに。
そんな思いで、私達は日々活動しています。
地域の皆さんに寄り添い、笑顔溢れるまちにしたいから。
私達と一緒に、長岡のまちを盛り上げていきましょう。
