### ISSUE TITLE
Google Formの雛形作成

### ISSUE THREAD

**Issue by gouten5010** [npo-skn-nagaoka/nagaokaplayers#19]
お問い合わせに利用するので作成してください。
設定に関してはフォームの編集自体を共有してもらうか、Zoomで画面共有しながらやりましょう。

**Comment by fukuda-nkyod** [comment]
https://docs.google.com/forms/d/1Zn6pFA8ZtD5Zbu5PyRMwRVF08jJ_hM_rHoOzsIKd7zs/edit?usp=sharing
