### ISSUE TITLE
フロントページ：入会・寄付への誘導リンク（ステートメント）配置

### ISSUE THREAD

**Issue by gouten5010** [npo-skn-nagaoka/nagaokaplayers#28]
1. 入会ページに遷移するボタンとステートメント
2. 夢の種ブロジェクトへの遷移するボタンと概要

**Comment by magu3** [comment]
長岡の今を知り、未来を作る会員を常時募集しています

私たちは、長岡市内のプレイヤーを支援するとともに、プレイヤー間の交流を深め、支え合い、高め合う風土を作っていく団体です。

会員になると、長岡で活動している団体との交流機会が増え、また、あなたの活動の情報発信機会が増えます。

もっと見る

**Comment by magu3** [comment]
長岡の今を知り、未来を作る会員を常時募集しています

私たちは、長岡のプレイヤーを支援するとともに、プレイヤー間の交流を深め、支え合い、高め合う風土を作っていく団体です。

会員になると、長岡で活動している団体との交流機会が増え、また、あなたの活動の情報発信機会が増えます。

もっと見る


さらに活力のあるまちに「夢の種プロジェクト」では寄付を募集しています

あなたの寄付で、長岡の未来が変わります。

夢のたねプロジェクトは、新たな取り組みをする市民に、集めた寄付金を支援金という形で贈呈していく仕組みです。

長岡をよりよくするために、柔軟で斬新なアイディアを実現するための活動資金が必要です。あなたの寄付を待っています。

もっと見る

**Comment by magu3** [comment]
長岡の未来を作るプレイヤーを応援しよう

柔軟で斬新なアイディアを実現していくプレイヤーは、長岡をさらに活力ある地域にするために不可欠な存在です。

長岡の街に点在するさまざなプレイヤーを知ることが応援に繋がります。

プレイヤーについてもっと知ろう


共に高め合う風土づくりに取り組みませんか？

私たちは、長岡のプレイヤーを支援するとともに、プレイヤー間の交流を深め、支え合い、高め合う風土を作っていくNPO法人です。

会員になると、長岡で活動している団体との交流機会が増え、また、あなたの活動の情報発信機会が増えます。

入会する
