### ISSUE TITLE
 ロゴのブラッシュアップ

### ISSUE THREAD

**Issue by gouten5010** [npo-skn-nagaoka/nagaokaplayers#36]
仮アップしているので、ちゃんとしたのを入れる

**Comment by miminari** [comment]
フクちゃんがブラッシュアップしてくれたので、OGPとキービジュアル差し替える

**Comment by miminari** [comment]
カラーレギュレーションの変更
https://www.figma.com/file/NQ4QZ6efam6fCZIP0knexF/colors?node-id=0%3A1

ロゴのブラッシュアップに伴いOGP / キービジュアル変更
https://www.figma.com/file/Gzu2Hte5ZcbFqOlHzLFuPn/LOGOS?node-id=0%3A1

**Comment by miminari** [comment]
<img width="1200" alt="Facebook Post - 1" src="https://user-images.githubusercontent.com/487207/82223244-5f69d100-995d-11ea-8cb1-52fdb7688197.png">

<img width="699" alt="key-visual01" src="https://user-images.githubusercontent.com/487207/82223714-f898e780-995d-11ea-8e6e-cd6a4b75c5da.png">

に本番サイト差し替え、再ジェネレイト済み
